"""add captcha model

Revision ID: 1fe94fd667d0
Revises: f24bcf788722
Create Date: 2026-05-16 11:43:22.156812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe94fd667d0'
down_revision: Union[str, Sequence[str], None] = 'f24bcf788722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captchas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captchas')
    # ### end Alembic commands ###
