"""add_sharing_fields

Revision ID: c9f56f4cedb7
Revises: 3a5dad7c1b91
Create Date: 2026-05-16 09:32:45.865557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f56f4cedb7'
down_revision: Union[str, Sequence[str], None] = '3a5dad7c1b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('sharing_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_sharing_token'), 'items', ['sharing_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_sharing_token'), table_name='items')
    op.drop_column('items', 'sharing_token')
    op.drop_column('items', 'is_public')
    # ### end Alembic commands ###
